In [1]:
import pandas as pd
from data_utils import extract_features
from dataset import ImageCaptionDataset
from tokenizers import Tokenizer

2024-01-13 15:59:39.411733: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-01-13 15:59:39.467571: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-01-13 15:59:39.468367: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-13 15:59:40.486341: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
df = pd.read_csv('data/captions.csv')
features = extract_features(df['image'].values.tolist())

2024-01-13 15:59:43.228458: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-13 15:59:43.229924: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
  0%|          | 0/100 [00:00<?, ?it/s]

1/1 [==============================] - 3s 3s/step


  1%|          | 1/100 [00:03<05:35,  3.39s/it]

1/1 [==============================] - 0s 155ms/step


  2%|▏         | 2/100 [00:03<02:30,  1.53s/it]

1/1 [==============================] - 0s 158ms/step


  3%|▎         | 3/100 [00:03<01:31,  1.06it/s]

1/1 [==============================] - 0s 148ms/step


  4%|▍         | 4/100 [00:04<01:03,  1.52it/s]

1/1 [==============================] - 0s 156ms/step


  5%|▌         | 5/100 [00:04<00:54,  1.74it/s]

1/1 [==============================] - 0s 168ms/step


  6%|▌         | 6/100 [00:04<00:44,  2.13it/s]

1/1 [==============================] - 0s 155ms/step


  7%|▋         | 7/100 [00:05<00:36,  2.53it/s]

1/1 [==============================] - 0s 154ms/step


  8%|▊         | 8/100 [00:05<00:31,  2.92it/s]

1/1 [==============================] - 0s 154ms/step


  9%|▉         | 9/100 [00:05<00:27,  3.26it/s]

1/1 [==============================] - 0s 156ms/step


 10%|█         | 10/100 [00:05<00:25,  3.51it/s]

1/1 [==============================] - 0s 154ms/step


 11%|█         | 11/100 [00:05<00:23,  3.71it/s]

1/1 [==============================] - 0s 153ms/step


 12%|█▏        | 12/100 [00:06<00:22,  3.84it/s]

1/1 [==============================] - 0s 192ms/step


 13%|█▎        | 13/100 [00:06<00:23,  3.70it/s]

1/1 [==============================] - 0s 156ms/step


 14%|█▍        | 14/100 [00:06<00:22,  3.85it/s]

1/1 [==============================] - 0s 147ms/step


 15%|█▌        | 15/100 [00:06<00:21,  4.03it/s]

1/1 [==============================] - 0s 152ms/step


 16%|█▌        | 16/100 [00:07<00:20,  4.11it/s]

1/1 [==============================] - 0s 157ms/step


 17%|█▋        | 17/100 [00:07<00:20,  4.11it/s]

1/1 [==============================] - 0s 147ms/step


 18%|█▊        | 18/100 [00:07<00:19,  4.25it/s]

1/1 [==============================] - 0s 151ms/step


 19%|█▉        | 19/100 [00:07<00:18,  4.31it/s]

1/1 [==============================] - 0s 185ms/step


 20%|██        | 20/100 [00:08<00:19,  4.12it/s]

1/1 [==============================] - 0s 153ms/step


 21%|██        | 21/100 [00:08<00:19,  4.12it/s]

1/1 [==============================] - 0s 155ms/step


 22%|██▏       | 22/100 [00:08<00:18,  4.14it/s]

1/1 [==============================] - 0s 150ms/step


 23%|██▎       | 23/100 [00:08<00:18,  4.18it/s]

1/1 [==============================] - 0s 164ms/step


 24%|██▍       | 24/100 [00:09<00:18,  4.15it/s]

1/1 [==============================] - 0s 218ms/step


 25%|██▌       | 25/100 [00:09<00:19,  3.80it/s]

1/1 [==============================] - 0s 187ms/step


 26%|██▌       | 26/100 [00:09<00:19,  3.71it/s]

1/1 [==============================] - 0s 148ms/step


 27%|██▋       | 27/100 [00:09<00:18,  3.92it/s]

1/1 [==============================] - 0s 164ms/step


 28%|██▊       | 28/100 [00:10<00:22,  3.27it/s]

1/1 [==============================] - 0s 200ms/step


 29%|██▉       | 29/100 [00:10<00:21,  3.32it/s]

1/1 [==============================] - 0s 149ms/step


 30%|███       | 30/100 [00:10<00:19,  3.56it/s]

1/1 [==============================] - 0s 146ms/step


 31%|███       | 31/100 [00:11<00:18,  3.81it/s]

1/1 [==============================] - 0s 146ms/step


 32%|███▏      | 32/100 [00:11<00:16,  4.01it/s]

1/1 [==============================] - 0s 148ms/step


 33%|███▎      | 33/100 [00:11<00:16,  4.11it/s]

1/1 [==============================] - 0s 159ms/step


 34%|███▍      | 34/100 [00:11<00:15,  4.19it/s]

1/1 [==============================] - 0s 157ms/step


 35%|███▌      | 35/100 [00:11<00:15,  4.20it/s]

1/1 [==============================] - 0s 200ms/step


 36%|███▌      | 36/100 [00:12<00:15,  4.03it/s]

1/1 [==============================] - 0s 149ms/step


 37%|███▋      | 37/100 [00:12<00:15,  4.09it/s]

1/1 [==============================] - 0s 154ms/step


 38%|███▊      | 38/100 [00:12<00:14,  4.18it/s]

1/1 [==============================] - 0s 146ms/step


 39%|███▉      | 39/100 [00:12<00:14,  4.30it/s]

1/1 [==============================] - 0s 150ms/step


 40%|████      | 40/100 [00:13<00:13,  4.37it/s]

1/1 [==============================] - 0s 147ms/step


 41%|████      | 41/100 [00:13<00:13,  4.42it/s]

1/1 [==============================] - 0s 146ms/step


 42%|████▏     | 42/100 [00:13<00:12,  4.47it/s]

1/1 [==============================] - 0s 144ms/step


 43%|████▎     | 43/100 [00:13<00:12,  4.53it/s]

1/1 [==============================] - 0s 167ms/step


 44%|████▍     | 44/100 [00:14<00:13,  4.22it/s]

1/1 [==============================] - 0s 148ms/step


 45%|████▌     | 45/100 [00:14<00:13,  4.21it/s]

1/1 [==============================] - 0s 149ms/step


 46%|████▌     | 46/100 [00:14<00:12,  4.30it/s]

1/1 [==============================] - 0s 151ms/step


 47%|████▋     | 47/100 [00:14<00:12,  4.31it/s]

1/1 [==============================] - 0s 145ms/step


 48%|████▊     | 48/100 [00:14<00:11,  4.40it/s]

1/1 [==============================] - 0s 152ms/step


 49%|████▉     | 49/100 [00:15<00:11,  4.35it/s]

1/1 [==============================] - 0s 151ms/step


 50%|█████     | 50/100 [00:15<00:11,  4.34it/s]

1/1 [==============================] - 0s 152ms/step


 51%|█████     | 51/100 [00:15<00:11,  4.40it/s]

1/1 [==============================] - 0s 200ms/step


 52%|█████▏    | 52/100 [00:15<00:11,  4.08it/s]

1/1 [==============================] - 0s 149ms/step


 53%|█████▎    | 53/100 [00:16<00:11,  4.16it/s]

1/1 [==============================] - 0s 151ms/step


 54%|█████▍    | 54/100 [00:16<00:10,  4.23it/s]

1/1 [==============================] - 0s 146ms/step


 55%|█████▌    | 55/100 [00:16<00:10,  4.22it/s]

1/1 [==============================] - 0s 155ms/step


 56%|█████▌    | 56/100 [00:16<00:10,  4.25it/s]

1/1 [==============================] - 0s 155ms/step


 57%|█████▋    | 57/100 [00:17<00:10,  4.28it/s]

1/1 [==============================] - 0s 149ms/step


 58%|█████▊    | 58/100 [00:17<00:09,  4.33it/s]

1/1 [==============================] - 0s 144ms/step


 59%|█████▉    | 59/100 [00:17<00:09,  4.42it/s]

1/1 [==============================] - 0s 153ms/step


 60%|██████    | 60/100 [00:17<00:09,  4.44it/s]

1/1 [==============================] - 0s 166ms/step


 61%|██████    | 61/100 [00:18<00:09,  4.16it/s]

1/1 [==============================] - 0s 152ms/step


 62%|██████▏   | 62/100 [00:18<00:09,  4.19it/s]

1/1 [==============================] - 0s 153ms/step


 63%|██████▎   | 63/100 [00:18<00:08,  4.28it/s]

1/1 [==============================] - 0s 152ms/step


 64%|██████▍   | 64/100 [00:18<00:08,  4.29it/s]

1/1 [==============================] - 0s 151ms/step


 65%|██████▌   | 65/100 [00:18<00:08,  4.35it/s]

1/1 [==============================] - 0s 149ms/step


 66%|██████▌   | 66/100 [00:19<00:07,  4.32it/s]

1/1 [==============================] - 0s 160ms/step


 67%|██████▋   | 67/100 [00:19<00:07,  4.28it/s]

1/1 [==============================] - 0s 155ms/step


 68%|██████▊   | 68/100 [00:19<00:07,  4.31it/s]

1/1 [==============================] - 0s 227ms/step


 69%|██████▉   | 69/100 [00:19<00:08,  3.84it/s]

1/1 [==============================] - 0s 153ms/step


 70%|███████   | 70/100 [00:20<00:07,  3.98it/s]

1/1 [==============================] - 0s 156ms/step


 71%|███████   | 71/100 [00:20<00:07,  4.07it/s]

1/1 [==============================] - 0s 157ms/step


 72%|███████▏  | 72/100 [00:20<00:06,  4.13it/s]

1/1 [==============================] - 0s 158ms/step


 73%|███████▎  | 73/100 [00:20<00:06,  4.16it/s]

1/1 [==============================] - 0s 148ms/step


 74%|███████▍  | 74/100 [00:21<00:06,  4.20it/s]

1/1 [==============================] - 0s 154ms/step


 75%|███████▌  | 75/100 [00:21<00:06,  4.17it/s]

1/1 [==============================] - 0s 156ms/step


 76%|███████▌  | 76/100 [00:21<00:05,  4.26it/s]

1/1 [==============================] - 0s 144ms/step


 77%|███████▋  | 77/100 [00:21<00:05,  4.31it/s]

1/1 [==============================] - 0s 172ms/step


 78%|███████▊  | 78/100 [00:22<00:05,  4.09it/s]

1/1 [==============================] - 0s 151ms/step


 79%|███████▉  | 79/100 [00:22<00:05,  4.14it/s]

1/1 [==============================] - 0s 163ms/step


 80%|████████  | 80/100 [00:22<00:04,  4.19it/s]

1/1 [==============================] - 0s 148ms/step


 81%|████████  | 81/100 [00:22<00:04,  4.30it/s]

1/1 [==============================] - 0s 159ms/step


 82%|████████▏ | 82/100 [00:23<00:04,  4.21it/s]

1/1 [==============================] - 0s 166ms/step


 83%|████████▎ | 83/100 [00:23<00:04,  4.21it/s]

1/1 [==============================] - 0s 154ms/step


 84%|████████▍ | 84/100 [00:23<00:03,  4.26it/s]

1/1 [==============================] - 0s 151ms/step


 85%|████████▌ | 85/100 [00:23<00:03,  4.24it/s]

1/1 [==============================] - 0s 200ms/step


 86%|████████▌ | 86/100 [00:24<00:03,  3.94it/s]

1/1 [==============================] - 0s 146ms/step


 87%|████████▋ | 87/100 [00:24<00:03,  4.10it/s]

1/1 [==============================] - 0s 154ms/step


 88%|████████▊ | 88/100 [00:24<00:02,  4.15it/s]

1/1 [==============================] - 0s 152ms/step


 89%|████████▉ | 89/100 [00:24<00:02,  4.27it/s]

1/1 [==============================] - 0s 149ms/step


 90%|█████████ | 90/100 [00:24<00:02,  4.31it/s]

1/1 [==============================] - 0s 150ms/step


 91%|█████████ | 91/100 [00:25<00:02,  4.38it/s]

1/1 [==============================] - 0s 158ms/step


 92%|█████████▏| 92/100 [00:25<00:01,  4.26it/s]

1/1 [==============================] - 0s 155ms/step


 93%|█████████▎| 93/100 [00:25<00:01,  4.28it/s]

1/1 [==============================] - 0s 211ms/step


 94%|█████████▍| 94/100 [00:25<00:01,  3.96it/s]

1/1 [==============================] - 0s 152ms/step


 95%|█████████▌| 95/100 [00:26<00:01,  4.13it/s]

1/1 [==============================] - 0s 144ms/step


 96%|█████████▌| 96/100 [00:26<00:00,  4.32it/s]

1/1 [==============================] - 0s 155ms/step


 97%|█████████▋| 97/100 [00:26<00:00,  4.32it/s]

1/1 [==============================] - 0s 157ms/step


 98%|█████████▊| 98/100 [00:26<00:00,  4.32it/s]

1/1 [==============================] - 0s 158ms/step


 99%|█████████▉| 99/100 [00:27<00:00,  4.32it/s]

1/1 [==============================] - 0s 155ms/step


100%|██████████| 100/100 [00:27<00:00,  3.66it/s]


In [3]:
tokenizer = Tokenizer.from_file(str('./tokenizer.json'))


dataloaded = ImageCaptionDataset(df, 'image', 'caption', 10, tokenizer, 30, features)
data = dataloaded.__getitem__(0)
data

{'encoder_output': <tf.Tensor: shape=(10, 1920), dtype=float32, numpy=
 array([[7.8687925e-05, 7.3524035e-04, 1.1395990e-03, ..., 5.6523436e-01,
         2.2903825e-01, 6.9639945e-01],
        [7.8687925e-05, 7.3524035e-04, 1.1395990e-03, ..., 5.6523436e-01,
         2.2903825e-01, 6.9639945e-01],
        [7.8687925e-05, 7.3524035e-04, 1.1395990e-03, ..., 5.6523436e-01,
         2.2903825e-01, 6.9639945e-01],
        ...,
        [1.2493611e-04, 4.5205691e-04, 1.9292447e-03, ..., 7.4857108e-02,
         2.0473881e+00, 9.0312645e-02],
        [1.2493611e-04, 4.5205691e-04, 1.9292447e-03, ..., 7.4857108e-02,
         2.0473881e+00, 9.0312645e-02],
        [1.2493611e-04, 4.5205691e-04, 1.9292447e-03, ..., 7.4857108e-02,
         2.0473881e+00, 9.0312645e-02]], dtype=float32)>,
 'decoder_input': <tf.Tensor: shape=(50, 30), dtype=int64, numpy=
 array([[  2,  43,   4, ...,   1,   1,   1],
        [  2,  19, 319, ...,   1,   1,   1],
        [  2,  40,  19, ...,   1,   1,   1],
        ...,


In [6]:
decoder_input_list = data['label'].numpy().tolist()

decoder_input_list[3] 


[40,
 19,
 119,
 5,
 398,
 20,
 60,
 2576,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [1]:
from train import train
from config import get_config
config = get_config()
train(config)

2024-01-13 16:08:02.666676: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-01-13 16:08:02.729661: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-01-13 16:08:02.731600: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-13 16:08:03.879016: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-01-13 16:08:05.888077: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Do

Max length of target sentence: 34
No weights found
++++++++ ['1000268201_693b08cb0e.jpg', '1000268201_693b08cb0e.jpg', '1000268201_693b08cb0e.jpg', '1000268201_693b08cb0e.jpg', '1000268201_693b08cb0e.jpg', '1001773457_577c3a7d70.jpg', '1001773457_577c3a7d70.jpg', '1001773457_577c3a7d70.jpg', '1001773457_577c3a7d70.jpg', '1001773457_577c3a7d70.jpg']
label: tf.Tensor(
[[ 43   4  91 ...   1   1   1]
 [ 19 319  65 ...   1   1   1]
 [ 40  19 119 ...   1   1   1]
 ...
 [ 15   9   8 ...   1   1   1]
 [ 13  31  12 ...   1   1   1]
 [ 13  31   6 ...   1   1   1]], shape=(50, 40), dtype=int64)
++++++++ ['1002674143_1b742ab4b8.jpg', '1002674143_1b742ab4b8.jpg', '1002674143_1b742ab4b8.jpg', '1002674143_1b742ab4b8.jpg', '1002674143_1b742ab4b8.jpg', '1003163366_44323f5815.jpg', '1003163366_44323f5815.jpg', '1003163366_44323f5815.jpg', '1003163366_44323f5815.jpg', '1003163366_44323f5815.jpg']
label: tf.Tensor(
[[ 40  19 166 ...   1   1   1]
 [ 40  19   7 ...   1   1   1]
 [ 53  19   4 ...   1   1   1

KeyError: '1024138940_f1fefbdce1.jpg'