In [5]:
import pandas as pd
from img_utils import extract_features
from dataset import ImageCaptionGenerator
from tokenizers import Tokenizer

In [6]:
df = pd.read_csv('data/captions.csv')
features = extract_features(df['image'].values.tolist())
features

  0%|          | 0/10 [00:00<?, ?it/s]

1/1 [==============================] - 4s 4s/step


 10%|█         | 1/10 [00:03<00:33,  3.70s/it]

1/1 [==============================] - 0s 152ms/step


 20%|██        | 2/10 [00:03<00:13,  1.65s/it]

1/1 [==============================] - 0s 152ms/step


 30%|███       | 3/10 [00:04<00:06,  1.00it/s]

1/1 [==============================] - 0s 153ms/step


 40%|████      | 4/10 [00:04<00:04,  1.45it/s]

1/1 [==============================] - 0s 183ms/step


 50%|█████     | 5/10 [00:04<00:02,  1.89it/s]

1/1 [==============================] - 0s 191ms/step


 60%|██████    | 6/10 [00:04<00:01,  2.29it/s]

1/1 [==============================] - 0s 178ms/step


 70%|███████   | 7/10 [00:05<00:01,  2.66it/s]

1/1 [==============================] - 0s 151ms/step


 80%|████████  | 8/10 [00:05<00:00,  3.06it/s]

1/1 [==============================] - 0s 216ms/step


 90%|█████████ | 9/10 [00:05<00:00,  3.20it/s]

1/1 [==============================] - 0s 169ms/step


100%|██████████| 10/10 [00:05<00:00,  1.71it/s]


{'1000268201_693b08cb0e.jpg': array([[7.8687925e-05, 7.3524035e-04, 1.1395990e-03, ..., 5.6523436e-01,
         2.2903825e-01, 6.9639945e-01]], dtype=float32),
 '1001773457_577c3a7d70.jpg': array([[1.2493611e-04, 4.5205691e-04, 1.9292447e-03, ..., 7.4857108e-02,
         2.0473881e+00, 9.0312645e-02]], dtype=float32)}

In [7]:
tokenizer = Tokenizer.from_file(str('./tokenizer.json'))


dataloaded = ImageCaptionGenerator(df, 'image', 'caption', 10, tokenizer, 30, features)
data = dataloaded.__getitem__(0)
data

[SOS] child in pink dress is climbing up set of stairs in an entry way [EOS]
decoder_input: (1, 30), dec_input: (1, 30)
[SOS] girl going into wooden building [EOS]
decoder_input: (2, 30), dec_input: (1, 30)
[SOS] little girl climbing into wooden playhouse [EOS]
decoder_input: (3, 30), dec_input: (1, 30)
[SOS] little girl climbing the stairs to her playhouse [EOS]
decoder_input: (4, 30), dec_input: (1, 30)
[SOS] little girl in pink dress going into wooden cabin [EOS]
decoder_input: (5, 30), dec_input: (1, 30)
[SOS] child in pink dress is climbing up set of stairs in an entry way [EOS]
decoder_input: (6, 30), dec_input: (1, 30)
[SOS] girl going into wooden building [EOS]
decoder_input: (7, 30), dec_input: (1, 30)
[SOS] little girl climbing into wooden playhouse [EOS]
decoder_input: (8, 30), dec_input: (1, 30)
[SOS] little girl climbing the stairs to her playhouse [EOS]
decoder_input: (9, 30), dec_input: (1, 30)
[SOS] little girl in pink dress going into wooden cabin [EOS]
decoder_input: 

{'encoder_input': <tf.Tensor: shape=(51, 1920), dtype=float32, numpy=
 array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00],
        [7.8687925e-05, 7.3524035e-04, 1.1395990e-03, ..., 5.6523436e-01,
         2.2903825e-01, 6.9639945e-01],
        [7.8687925e-05, 7.3524035e-04, 1.1395990e-03, ..., 5.6523436e-01,
         2.2903825e-01, 6.9639945e-01],
        ...,
        [1.2493611e-04, 4.5205691e-04, 1.9292447e-03, ..., 7.4857108e-02,
         2.0473881e+00, 9.0312645e-02],
        [1.2493611e-04, 4.5205691e-04, 1.9292447e-03, ..., 7.4857108e-02,
         2.0473881e+00, 9.0312645e-02],
        [1.2493611e-04, 4.5205691e-04, 1.9292447e-03, ..., 7.4857108e-02,
         2.0473881e+00, 9.0312645e-02]], dtype=float32)>,
 'decoder_input': <tf.Tensor: shape=(51, 30), dtype=int64, numpy=
 array([[  0,   0,   0, ...,   0,   0,   0],
        [  2,  43,   4, ...,   1,   1,   1],
        [  2,  19, 319, ...,   1,   1,   1],
        ...,
 

[[0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [2,
  43,
  4,
  91,
  174,
  7,
  119,
  51,
  397,
  12,
  398,
  4,
  28,
  0,
  683,
  3,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [2,
  19,
  319,
  65,
  198,
  118,
  3,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [2,
  40,
  19,
  119,
  65,
  198,
  2576,
  3,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [2,
  40,
  19,
  119,
  5,
  398,
  20,
  60,
  2576,
  3,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [2,
  40,
  19,
  4,
  91,
  174,
  319,
  65,
  198,
  3046,
  3,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [2,
  43,
  4,
  91,
  174,
  7,
  1